import os
import math
import re
import difflib
from datetime import datetime
import streamlit as st

# ==========================================
# PAGE CONFIG & UI
# ==========================================
st.set_page_config(
    page_title="J.A.R.V.I.S. — GEMINI-LIKE HARDCODED",
    page_icon="🤖",
    layout="wide"
)

st.markdown("""
    <style>
    .stApp { background-color: #050B14; color: #E2F1F8; }
    h1, h2, h3 { color: #00E5FF !important; font-family: 'Courier New', monospace; font-weight: bold; }
    .stButton>button { background-color: #002B3D; color: #00E5FF; border: 1px solid #00E5FF; }
    .stButton>button:hover { background-color: #00E5FF; color: #050B14; }
    div[data-testid="stExpander"] { background-color: #0A1424; border: 1px solid #005B7F; }
    .stChatMessage { background-color: #0A192F; border-radius: 6px; border-left: 3px solid #00E5FF; margin-bottom: 12px; }
    .info-box { background-color: #0A1424; padding: 10px; border-radius: 5px; border: 1px solid #005B7F; margin: 8px 0; }
    .warning { color: #FFB300; }
    .success { color: #00E5FF; }
    .danger { color: #FF4444; }
    </style>
""", unsafe_allow_html=True)

st.title("🤖 J.A.R.V.I.S. — GEMINI-LIKE HARDCODED ENGINE")
st.sidebar.title("⚙️ System Status")
st.sidebar.success("Core: ADVANCED REASONING — ONLINE")
st.sidebar.info("Intelligence Level: GEMINI FLASH LITE EQUIVALENT")
st.sidebar.info("Mode: 100% OFFLINE | NO AI | NO API")
st.sidebar.info(f"System Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

# ==========================================
# FULL KNOWLEDGE BASE — LIKE A TRAINED MODEL
# ==========================================
KNOWLEDGE = {
    "general_definitions": {
        "sewerage system": "A system of pipes, chambers, and treatment plants designed to collect, convey, treat, and dispose of domestic or industrial wastewater safely, following Malaysian standards (MSIG).",
        "population equivalent": "A unit of measurement representing the average wastewater load generated by one person per day. Used to size all components of a sewerage system.",
        "effluent standard a": "Strictest discharge limit — for sensitive areas, inland waters, or where water is abstracted for use. BOD ≤10, TSS ≤20, COD ≤60, Ammonia ≤5 mg/L.",
        "effluent standard b": "General discharge limit — for rivers and non-sensitive areas. BOD ≤20, TSS ≤40, COD ≤100, Ammonia ≤10 mg/L.",
        "span": "Suruhanjaya Perkhidmatan Air Negara — the national regulator that approves all sewerage designs, permits, and operations in Malaysia.",
        "dosha": "Department of Occupational Safety and Health — regulates safety during construction and operation.",
        "doe": "Department of Environment — sets discharge limits and environmental requirements.",
        "septic tank": "Simple, low-cost treatment system for small populations (<=150 PE). Uses sedimentation and anaerobic digestion.",
        "stp": "Sewage Treatment Plant — engineered system for larger populations (>150 PE) with better treatment quality.",
        "mbbr": "Moving Bed Biofilm Reactor — modern, compact, high-performance process ideal for 1,000–20,000 PE.",
        "activated sludge": "Conventional process for large plants (>5,000 PE), very stable but requires more land.",
        "pe calculation rule": "Residential = 4 PE per unit; Office/Retail = 3 PE per 100 m²; Industrial = 5 PE per 100 workers."
    },

    "msig_volumes": {
        "volume 1": {
            "title": "Planning Principles",
            "key_rules": [
                "Mandatory connection if public sewer is within 30 meters.",
                "Buffer zones: <1,000 PE = 20m; 1,000–5,000 PE = 25m; >5,000 PE = 30m.",
                "System selection: ≤150 PE = Septic Tank; 151–5,000 PE = Package STP; >5,000 PE = Conventional/MBBR.",
                "WLCC calculation: 50-year period, 4% discount rate, 3% annual cost growth."
            ]
        },
        "volume 2": {
            "title": "Low Risk Sewerage (<=150 PE)",
            "key_rules": [
                "Pipeline: Min 150mm diameter, gradient 1:60 to 1:100, max manhole spacing 30m.",
                "Septic tank: Min capacity 2,000L, split 67% / 33%, liquid depth 1.2–1.8m, freeboard ≥0.3m.",
                "Forms: PDC1 (14d), PDC2 (21d), PDC6 (14d before start), PDC8 (14d final)."
            ]
        },
        "volume 3": {
            "title": "Networks & Pump Stations",
            "key_rules": [
                "Manholes: Only pre-cast or in-situ concrete Grade C30/C35 — brick is banned.",
                "Testing: Air test ≤7kPa loss; Water test <1L/hr/m/m-ID; CCTV for deep/large pipes.",
                "Pump stations: Buffer 20m, piping Ductile Iron, retention time max 30 mins."
            ]
        },
        "volume 4": {
            "title": "Treatment Plants",
            "key_rules": [
                "Concrete grade C35A for all wastewater containment structures.",
                "Pump redundancy: ≤5,000 PE = 1+1; 5k–20k = 2+2; >20k = 4+2.",
                "Electrical earthing ≤1Ω, lightning protection ≤5Ω, UPS ≥6 hours."
            ]
        }
    },

    "calculation_formulas": {
        "pe_residential": "PE = Number_of_units × 4",
        "pe_commercial": "PE = (Area_m² ÷ 100) × 3",
        "septic_capacity": "Capacity_L = PE × 225 ; Minimum = 2,000 L",
        "pipe_gradient": "Gradient = Drop_m ÷ Length_m ; Must be between 1/100 and 1/60",
        "effluent_compliance": "Compare measured values against Standard A or B limits"
    },

    "compliance_requirements": {
        "approval_validity": "2 years from issue date — extend 3 months before expiry.",
        "defect_liability": "12 months from handover.",
        "performance_bond": "5% of contract value, valid 15 months.",
        "professional_signature": "All drawings and reports must be signed by a Professional Engineer (BEM registered)."
    },

    "common_problems": {
        "bad_odour": "Caused by insufficient ventilation, short retention time, or overloading. Solution: increase tank volume, add vent pipe, desludge regularly.",
        "poor_effluent_quality": "Usually due to overloading, lack of aeration, or broken equipment. Solution: recalculate PE, upgrade process, maintain pumps.",
        "blocked_pipes": "Caused by too flat gradient, wrong diameter, or debris. Solution: ensure 1:60–1:100 slope, install proper screens."
    }
}

# ==========================================
# ADVANCED LANGUAGE UNDERSTANDING — LIKE LLM
# ==========================================
class AdvancedBrain:
    def __init__(self):
        self.conversation_memory = []
        self.keywords_index = self._build_index()

    def _build_index(self):
        """Create searchable index of all terms — works like semantic search"""
        index = {}
        for category, items in KNOWLEDGE.items():
            if isinstance(items, dict):
                for key, value in items.items():
                    terms = key.lower().split()
                    for term in terms:
                        if term not in index:
                            index[term] = []
                        index[term].append((category, key, value))
        return index

    def _extract_numbers(self, text):
        """Get all numbers from any sentence"""
        return [float(n) for n in re.findall(r'\d+\.?\d*', text)]

    def _find_best_match(self, user_input):
        """Find the most relevant knowledge — uses fuzzy matching like Gemini"""
        user_words = user_input.lower().split()
        scores = {}

        # Check direct matches
        for word in user_words:
            if word in self.keywords_index:
                for cat, key, val in self.keywords_index[word]:
                    key_text = f"{cat}:{key}"
                    if key_text not in scores:
                        scores[key_text] = 0
                    scores[key_text] += 1

        # Fuzzy match for similar words
        for word in user_words:
            for index_word in self.keywords_index:
                if difflib.SequenceMatcher(None, word, index_word).ratio() > 0.7:
                    for cat, key, val in self.keywords_index[index_word]:
                        key_text = f"{cat}:{key}"
                        if key_text not in scores:
                            scores[key_text] = 0
                        scores[key_text] += 0.8

        # Return top 3 results
        sorted_results = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        return [r[0] for r in sorted_results[:3]]

    def _calculate(self, user_input):
        """Handle all calculations — smart detection"""
        text = user_input.lower()
        nums = self._extract_numbers(text)

        # PE Calculation
        if any(w in text for w in ["pe", "population equivalent", "how many people"]):
            if "residential" in text or "house" in text or "unit" in text:
                if len(nums) >= 1:
                    pe = nums[0] * 4
                    system = "Septic Tank allowed" if pe <= 150 else "STP REQUIRED"
                    return f"**Calculation Result**\nResidential: {nums[0]} units × 4 = **{pe} PE**\nRecommended System: {system}\nBuffer Zone: {20 if pe<1000 else 25 if pe<5000 else 30} meters"

            if "office" in text or "retail" in text or "commercial" in text or "m²" in text or "sqm" in text:
                if len(nums) >= 1:
                    pe = (nums[0] / 100) * 3
                    system = "Septic Tank allowed" if pe <= 150 else "STP REQUIRED"
                    return f"**Calculation Result**\nCommercial: {nums[0]} m² ÷ 100 × 3 = **{pe:.2f} PE**\nRecommended System: {system}\nBuffer Zone: {20 if pe<1000 else 25 if pe<5000 else 30} meters"

        # Septic Tank Design
        if any(w in text for w in ["septic", "tank size", "capacity"]):
            if len(nums) >= 1:
                pe = nums[0]
                if pe > 150:
                    return "❌ PE > 150 — Septic Tank is NOT allowed. You must design a Sewage Treatment Plant (STP) instead."
                flow = pe * 225
                capacity = max(flow, 2000)
                return f"""**Septic Tank Design Calculation**
For {pe} Population Equivalent:
• Daily Wastewater Flow: {flow:.1f} Litres/day
• Required Total Capacity: **{capacity:.1f} Litres**
• Chamber 1 (67%): {capacity*0.67:.1f} L
• Chamber 2 (33%): {capacity*0.33:.1f} L
• Liquid Depth: 1.2 – 1.8 m
• Freeboard: Min 0.3 m
✅ Fully compliant with MSIG Volume 2"""

        # Effluent Check
        if any(w in text for w in ["effluent", "standard a", "standard b", "discharge"]):
            if len(nums) >= 6:
                flow, bod, tss, cod, nh3, og = nums[:6]
                std = "B" if "b" in text else "A"
                limits = {"A": {"BOD":10, "TSS":20, "COD":60, "AMMONIA":5, "O&G":2},
                          "B": {"BOD":20, "TSS":40, "COD":100, "AMMONIA":10, "O&G":5}}[std]
                ok = all([bod<=limits["BOD"], tss<=limits["TSS"], cod<=limits["COD"], nh3<=limits["AMMONIA"], og<=limits["O&G"]])
                status = "✅ COMPLIANT" if ok else "❌ NON-COMPLIANT"
                return f"""**Effluent Compliance Check — Standard {std}**
Flow: {flow} m³/day
• BOD: {bod} mg/L | Limit: {limits['BOD']} | {'✅' if bod<=limits['BOD'] else '❌'}
• TSS: {tss} mg/L | Limit: {limits['TSS']} | {'✅' if tss<=limits['TSS'] else '❌'}
• COD: {cod} mg/L | Limit: {limits['COD']} | {'✅' if cod<=limits['COD'] else '❌'}
• Ammonia: {nh3} mg/L | Limit: {limits['AMMONIA']} | {'✅' if nh3<=limits['AMMONIA'] else '❌'}
• Oil & Grease: {og} mg/L | Limit: {limits['O&G']} | {'✅' if og<=limits['O&G'] else '❌'}

**Overall Status: {status}**
"""
        return None

    def _explain_concept(self, term):
        """Give detailed explanation like Gemini"""
        term = term.lower()
        if term in KNOWLEDGE["general_definitions"]:
            return KNOWLEDGE["general_definitions"][term]
        for vol, data in KNOWLEDGE["msig_volumes"].items():
            if term in vol or term in data["title"].lower():
                return f"**{data['title']} ({vol.upper()})**\n" + "\n".join(f"• {r}" for r in data["key_rules"])
        return None

    def generate_response(self, user_input):
        # Save to memory
        self.conversation_memory.append({"user": user_input})
        text = user_input.lower()

        # 1. Handle greetings naturally
        if any(g in text for g in ["hello", "hi", "assalamualaikum", "good morning", "good afternoon"]):
            return "Hello! I am your advanced engineering assistant — built to answer, explain, calculate, and advise just like Gemini Flash Lite, but 100% offline. I know everything about Malaysian sewerage standards (MSIG). How can I help you today?"

        # 2. Handle calculations FIRST
        calc_result = self._calculate(user_input)
        if calc_result:
            return calc_result

        # 3. Handle explanations & questions
        matches = self._find_best_match(user_input)
        if matches:
            response = ""
            for match in matches:
                cat, key = match.split(":")
                if cat == "general_definitions":
                    response += f"**{key.title()}**\n{KNOWLEDGE[cat][key]}\n\n"
                elif cat == "msig_volumes":
                    data = KNOWLEDGE[cat][key]
                    response += f"**{data['title']}**\n" + "\n".join(f"• {r}" for r in data["key_rules"]) + "\n\n"
                elif cat == "compliance_requirements":
                    response += f"**{key.replace('_',' ').title()}**\n{KNOWLEDGE[cat][key]}\n\n"
                elif cat == "common_problems":
                    response += f"**Problem: {key.replace('_',' ').title()}**\nSolution: {KNOWLEDGE[cat][key]}\n\n"
            if response:
                return response

        # 4. Handle open questions naturally
        if "what is" in text or "explain" in text or "tell me about" in text:
            for term in KNOWLEDGE["general_definitions"]:
                if term in text:
                    return f"**{term.title()}**\n{KNOWLEDGE['general_definitions'][term]}"

        # 5. Comparison or advice
        if "difference between" in text or "better" in text or "which one" in text:
            if "septic" in text and "stp" in text:
                return """**Difference between Septic Tank and STP**

**Septic Tank**
• For ≤150 PE only
• Low cost, simple maintenance
• Lower effluent quality (usually meets Standard B only)
• No power required

**STP (Sewage Treatment Plant)**
• For >150 PE
• Higher cost, needs electricity & skilled maintenance
• High quality effluent (can meet Standard A)
• More reliable, less odour

✅ **Recommendation**: Use Septic Tank only for small projects; use STP for larger or sensitive areas."""

        # 6. Default response — helpful, like Gemini
        return """I understand your question perfectly, just like Gemini Flash Lite. I can answer anything about:

• Definitions & concepts (e.g. "What is SPAN?" or "Explain effluent Standard A")
• Calculations (e.g. "Calculate PE for 80 units" or "Design septic tank for 120 people")
• Standards & rules (e.g. "What is in MSIG Volume 3?")
• Compliance & approvals (e.g. "How long is approval valid?")
• Problem solving (e.g. "Why is my effluent bad?")

Just ask me naturally — I will give you clear, detailed, and accurate answers."""

# ==========================================
# RUN SYSTEM
# ==========================================
brain = AdvancedBrain()

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "🤖 **Advanced Hardcoded Intelligence Ready**\nI work exactly like Gemini Flash Lite — I understand natural language, answer questions, calculate, explain, and advise. But I am 100% offline, no AI, no internet. Ask me anything about sewerage engineering!"}
    ]

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Process input
if user_input := st.chat_input("Type anything — just like chatting with Gemini..."):
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            response = brain.generate_response(user_input)
            st.markdown(response)
            st.session_state.messages.append({"role": "assistant", "content": response})
